name: Generate changelog
on:
  release:
    types: ["published"]
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: ./.github/actions/sphere-changelog
        with:
          filename: pricing-intelligence.json
          sphere_repository: pgmarc/SPHERE
          sphere_token: ${{ secrets.SPHERE_PAT_TOKEN }}
