name: Generate changelog
on:
  release:
    types: ["published"]
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0

      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      - name: Generate a CHANGELOG (JSON)
        id: git-cliff-json
        run: |
          git cliff --context --output context.json
          jq --compact-output --from-file jq/prune-changelog.jq context.json > context.json
          echo "context=$(cat context.json)" >> "$GITHUB_OUTPUT"

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          repository: pgmarc/SPHERE
          token: ${{ secrets.SPHERE_PAT_TOKEN }}

      - name: Upload CHANGELOG (JSON) to SPHERE repository
        run: |
          cd frontend/src/modules/presentation/pages/changelog
          cat <<EOF > pricing-intelligence.json
          ${{ steps.git-cliff-json.outputs.context }}
          EOF
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pricing-intelligence.json
          git commit -m "Update Pricing-Intelligence CHANGELOG" -n
          git push

